name: Build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55.2
    - name: Build
      run: make build-all
    - run: touch .env
    - run: bin/dataworks-helper_linux-amd64 --help
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true
    - run: make compress-linux
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/dataworks-helper*
        retention-days: 3
